name = "Lowess"
uuid = "a2847a04-7795-4581-bff1-964344ea125d"
authors = ["Ayush Patnaik, Siddhant Chaudhary, xKDR Forum"]
version = "0.1.0"

[deps]
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
